# Generated by Django 4.1.4 on 2022-12-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, max_length=10)),
                ('stock', models.CharField(max_length=100)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
